---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: main

      - name: Convert
        uses: docker://pandoc/latex:latest
        with:
          args: >-  # allows you to break string into multiple lines
            -s presentation.md  
            --pdf-engine=xelatex
            --citeproc
            -o report.pdf
            
      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.pdf